Add nuke whitespace options

diff --git a/dictpopup b/dictpopup
--- a/dictpopup
+++ b/dictpopup
@@ -13,8 +13,10 @@ readonly ANKI_WORD_FIELD=${ANKI_WORD_FIELD:-VocabKanji}
 readonly ANKI_DEFINITION_FIELD=${ANKI_DEFINITION_FIELD:-VocabDef}
 
 HTML_SUPPORT=1
-ANKI_SUPPORT=0
+ANKI_SUPPORT=1
 ANKI_SEARCH_AFTER_ADD=1
+NUKE_NEWLINES=1
+NUKE_SPACES=1
 ####
 
 die() {
@@ -59,8 +61,8 @@ anki_search() {
 }
 
 create_anki_card() {
-	local word=$(__escape_json "$1")
-	local definition="$2"
+	local word=$(__escape_json "$1") || true
+	local definition=$2
 	# Remove first line if it contains 【
 	if echo "$definition" | head -n 1 | grep -q "【"; then
 		definition=$(echo "$definition" | tail -n +2)
@@ -69,7 +71,11 @@ create_anki_card() {
 
 	notify-send "Please select the sentence"
 	clipnotify && sentence=$(xclip -o 2>/dev/null)
-	sentence=$(__escape_json "${sentence/$word/<b>$word</b>}")
+	[ $NUKE_NEWLINES -eq 1 ] && sentence=${sentence//$'\n'/}
+	[ $NUKE_SPACES -eq 1 ] && sentence=${sentence// /}
+	echo "$sentence"
+	sentence=${sentence/$word/<b>$word</b>}
+	sentence=$(__escape_json "$sentence")
 
 	local request=$(
 		cat <<-EOF
@@ -96,8 +102,14 @@ create_anki_card() {
 	)
 
 	if output=$(__ankiconnect_request "$request" 2>&1); then
-		note_id=$(echo "$output" | grep -o '"result": [0-9]*' | cut -d ' ' -f 2 | sed 's/[^0-9]//g')
-		[ $ANKI_SEARCH_AFTER_ADD -eq 1 ] && anki_search "$note_id"
+		if [ $ANKI_SEARCH_AFTER_ADD -eq 1 ]; then
+			note_id=$(echo "$output" | grep -o '"result": [0-9]*' | cut -d ' ' -f 2 | sed 's/[^0-9]//g')
+			if [ -n "$note_id" ]; then
+				anki_search "$note_id"
+			else
+				die "Error extracting note id."
+			fi
+		fi
 	else
 		die "$output"
 	fi
@@ -112,7 +124,7 @@ main() {
 		dict_entry=$(sdcv -n --utf8-output -e "$word" | format_output)
 	fi
 
-	printf "$dict_entry" | popup
+	printf "%s" "$dict_entry" | popup
 
 	[ $? -eq 2 ] && [ $ANKI_SUPPORT -eq 1 ] && create_anki_card "$word" "$dict_entry"
 }
